### PR TITLE
Update to avoid deprecated library in `package:web` v0.4.1

### PR DESCRIPTION
**Pull request by parlough**
\cc @devoncarew @srujzs Since this is breaking the Flutter tree.

### CODE REVIEW

**Review by srujzs — APPROVED** [review]

**Comment by srujzs** [comment]
@devoncarew It's possible we might end up breaking more stuff here - should we release this as a `0.5.0` instead? We can redact and then revert the change in the Dart SDK, but maybe that boat has sailed.

**Comment by parlough** [comment]
Yeah I guess this might cause issues for `flutter/packages` as well, but I'm not sure what their usages look like.

I suppose we should have released `0.4.1` with `package:web/web.dart` exporting the helpers, migrate the Flutter usages, then release `0.4.2` or `0.5.0` deprecating the helpers?

Do you think you want to redact or should I merge this?

**Comment by QuncCccccc** [comment]
Waiting for some advice to unblock the tree🙂

**Comment by srujzs** [comment]
I think a lot of `flutter/packages` use `package:web`, but I think their constraints look more like `>=0.3.0 <0.5.0` so I'm not sure if they'll hit this or not.

For now, let's push this through and fix the breakage first. @kevmoo

**Comment by devoncarew** [comment]
@parlough - thanks for the fix!

I'm inclined to fix this forward in the breakages we see. We do need to be able to message that there will be future API changes via `deprecation` annotations. That's challenging to reconcile w/ CIs that fail w/ new deprecation usages.

Perhaps for package:web we should deprecate in a new major version, and remove in the next? Or, default deprecation usages to not fail analysis w/o a `--fail-on-deprecation` flag to `dart analyze`.

**Comment by srujzs** [comment]
> Perhaps for package:web we should deprecate in a new major version, and remove in the next? Or, default deprecation usages to not fail analysis w/o a --fail-on-deprecation flag to dart analyze.

Going forward that makes sense, but that may lead to excessive versions. Flutter might end up likely using that flag anyways, so it'll still be a matter of fixing when updating versions.

**Comment by parlough** [comment]
I don't think Flutter's testing should prevent `package:web` from evolving, but yeah I think most of Flutter's CI checks don't allow deprecation.

So it'll end up like the SDK which has to fix all deprecations in Flutter before landing the deprecations, or the packages will need tighter constraints.

**Comment by devoncarew** [comment]
> package:web's CI might benefit from the customer testing that the analyzer has?

That would certainly be useful - it would give us advance awareness of the impact of breaking changes.

> So it'll end up like the SDK which has to fix all deprecated usages in Flutter (and siblings) before landing the deprecations

I think that's reasonable, but we wouldn't need to do that on a publish. Flutter uses specific versions of packages, so won't be broken on new deprecation messages (on publish); just when you go to use that specific version in the repo.

I suspect that the devtools repo is not using pubspec.lock files, so is getting the last published compatible version of a package.

**Comment by parlough** [comment]
> I think that's reasonable, but we wouldn't need to do that on a publish. Flutter uses specific versions of packages, so won't be broken on new deprecation messages (on publish); just when you go to use that specific version in the repo.

It looks like `flutter/packages` is blocked now as well since they use `package:web` with a wider constraint and run an analysis that fails on deprecated usages: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20analyze%20master/5315/overview

**Pull request merged**
