### PR TITLE
analyze package:devtools_server, package:split on the bots

### PR DESCRIPTION
**Pull request by devoncarew**
- analyze package:devtools_server and package:split on the bots

### CODE REVIEW

**Comment by devoncarew** [comment]
Screen Shot 2019-08-10 at 6 46 28 AM

**Comment by DanTup** [comment]
@devoncarew is it expected that this only runs the `packages` bot for Linux? I can't tell why it's doing that (maybe `include` doesn't multiply for the OSes?) but if it's not expected, we may want to add `packages` to the main `env` list and the `exclude` the `stable` one.

**Comment by devoncarew** [comment]
This is just doing dart analysis, so I think it's ok that it only runs for one platform. We have a very large number of config running currently.

**Comment by DanTup** [comment]
Yeah, sounds good to me. It wasn't obvious (to me) it'd only run on one from the yaml, so I thought I'd merged it badly when resolving a conflict, but it seems consistent with the build here. Thanks!

**Pull request merged**
