### PR TITLE
minor fix in my_application.h file

### PR DESCRIPTION
**Pull request by kapilkumar2001**

### CODE REVIEW

**Comment by kapilkumar2001** [comment]
@googlebot I signed it!

**Comment by jacob314** [comment]
What problem was that line causing? We didn't manually create that file. Has the code in Flutter to create this file been changed?

**Comment by kapilkumar2001** [comment]
No, Actually this line was giving an error because of that semicolon. I have added that semicolon so it will work fine now. I think this is coming from template code, I have opened a PR on flutter/flutter for this :)

**Comment by Hixie** [comment]
This doesn't seem right. Looking at the docs for G_DECLARE_FINAL_TYPE it doesn't suggest using a semicolon there either. (I couldn't find the definition of that macro with a quick Google search.)

**Comment by Hixie** [comment]
Since there's been no progress here since November I'm going to close this PR. Please don't hesitate to open a new one if this is still something you want to work on!

**Pull request closed without merging**
