### PR TITLE
Tweak Windows instructions to mirror macOS

### PR DESCRIPTION
**Pull request by DanTup**
@CoderDake @kenzieschmoll this tweaks the Windows setup to be the same as the macOS version:

https://github.com/CoderDake/devtools/assets/1078012/82ae3cc2-4dc7-4a0e-80ae-d8c526d46809

Error codes are also propagated as expected:

Screenshot 2023-09-28 145600

Screenshot 2023-09-28 145730

### CODE REVIEW

**Review by CoderDake — APPROVED** [review]
Thanks so much for looking into this Danny!

**Comment by DanTup** [comment]
Pushed a minor change (`@echo off`) to stop the commands being printed as they run

image

**Comment by DanTup** [comment]
Re-running failed bot that had this error - unsure if it's a flake or something broken:

```
2023-09-28T15:14:28.2586330Z FlutterDriveProcess - Got dependencies!
2023-09-28T15:14:28.2587400Z FlutterDriveProcess - 21 packages have newer versions incompatible with dependency constraints.
2023-09-28T15:14:28.2588500Z FlutterDriveProcess - Try `flutter pub outdated` for more information.
2023-09-28T15:14:29.0733960Z FlutterDriveProcess - Launching integration_test/test/live_connection/service_connection_test.dart on Web Server in debug mode...
2023-09-28T15:15:31.2432190Z FlutterDriveProcess - Waiting for connection from debug service on Web Server...         61.6s
2023-09-28T15:15:31.4831880Z FlutterDriveProcess - integration_test/test/live_connection/service_connection_test.dart is being served at http://localhost:49431
2023-09-28T15:15:31.4833420Z FlutterDriveProcess - The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
2023-09-28T15:17:42.7488790Z FlutterDriveProcess - result {"result":"false","failureDetails":["{\"methodName\":\"can call services and service extensions\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following assertion was thrown running a test:\\nAssertion failed:\\nfile:///Users/runner/work/devtools/devtools/packages/devtools_app/lib/src/shared/preferences.dart:335:12\\n_mainScriptDir != null\\nis not true\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3                               throw_\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3                                assertFailed\\npackages/devtools_app/src/shared/environment_parameters/environment_parameters_external.dart.js 72597:53  [_customPubRootStorageId]\\npackages/devtools_app/src/shared/environment_parameters/environment_parameters_external.dart.js 72552:82  [_persistCustomPubRootDirectoriesToStorage]\\npackages/devtools_app/src/shared/environment_parameters/environment_parameters_external.dart.js 72590:64  <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                                        <fn>\\ndart-sdk/lib/async/zone.dart 1407:47                                                                      _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1308:19                                                                      runUnary\\ndart-sdk/lib/async/future_impl.dart 162:18                                                                handleValue\\ndart-sdk/lib/async/future_impl.dart 846:44                                                                handleValueCallback\\ndart-sdk/lib/async/future_impl.dart 875:13                                                                _propagateToListeners\\ndart-sdk/lib/async/future_impl.dart 647:5                                                                 [_completeWithValue]\\ndart-sdk/lib/async/future_impl.dart 721:7                                                                 <fn>\\ndart-sdk/lib/async/zone.dart 1399:13                                                                      _rootRun\\ndart-sdk/lib/async/zone.dart 1301:19                                                                      run\\ndart-sdk/lib/async/zone.dart 1209:7                                                                       runGuarded\\ndart-sdk/lib/async/zone.dart 1249:23                                                                      callback\\ndart-sdk/lib/async/schedule_microtask.dart 40:11                                                          _microtaskLoop\\ndart-sdk/lib/async/schedule_microtask.dart 49:5                                                           _startMicrotaskLoop\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                                        <fn>\\n\\nThe test description was:\\n  can call services and service extensions\\n═════════════════════════════════════════════════════════════════\\n\"}"]}
2023-09-28T15:17:42.7613270Z FlutterDriveProcess - Failure Details:
2023-09-28T15:17:42.7707620Z FlutterDriveProcess - Failure in method: can call services and service extensions
2023-09-28T15:17:42.7750240Z FlutterDriveProcess - ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
2023-09-28T15:17:42.7751370Z FlutterDriveProcess - The following assertion was thrown running a test:
2023-09-28T15:17:42.7752520Z FlutterDriveProcess - Assertion failed:
2023-09-28T15:17:42.7753300Z FlutterDriveProcess - file:///Users/runner/work/devtools/devtools/packages/devtools_app/lib/src/shared/preferences.dart:335:12
2023-09-28T15:17:42.7753840Z FlutterDriveProcess - _mainScriptDir != null
2023-09-28T15:17:42.7754310Z FlutterDriveProcess - is not true
2023-09-28T15:17:42.7754630Z FlutterDriveProcess - 
2023-09-28T15:17:42.7755060Z FlutterDriveProcess - When the exception was thrown, this was the stack:
2023-09-28T15:17:42.7755700Z FlutterDriveProcess - dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3                               throw_
2023-09-28T15:17:42.7756350Z FlutterDriveProcess - dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3                                assertFailed
2023-09-28T15:17:42.7757080Z FlutterDriveProcess - packages/devtools_app/src/shared/environment_parameters/environment_parameters_external.dart.js 72597:53  [_customPubRootStorageId]
2023-09-28T15:17:42.7757910Z FlutterDriveProcess - packages/devtools_app/src/shared/environment_parameters/environment_parameters_external.dart.js 72552:82  [_persistCustomPubRootDirectoriesToStorage]
2023-09-28T15:17:42.7758700Z FlutterDriveProcess - packages/devtools_app/src/shared/environment_parameters/environment_parameters_external.dart.js 72590:64  <fn>
2023-09-28T15:17:42.7759360Z FlutterDriveProcess - dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                                        <fn>
2023-09-28T15:17:42.7759980Z FlutterDriveProcess - dart-sdk/lib/async/zone.dart 1407:47                                                                      _rootRunUnary
2023-09-28T15:17:42.7760560Z FlutterDriveProcess - dart-sdk/lib/async/zone.dart 1308:19                                                                      runUnary
2023-09-28T15:17:42.7761150Z FlutterDriveProcess - dart-sdk/lib/async/future_impl.dart 162:18                                                                handleValue
2023-09-28T15:17:42.7761780Z FlutterDriveProcess - dart-sdk/lib/async/future_impl.dart 846:44                                                                handleValueCallback
2023-09-28T15:17:42.7762480Z FlutterDriveProcess - dart-sdk/lib/async/future_impl.dart 875:13                                                                _propagateToListeners
2023-09-28T15:17:42.7763120Z FlutterDriveProcess - dart-sdk/lib/async/future_impl.dart 647:5                                                                 [_completeWithValue]
2023-09-28T15:17:42.7764690Z FlutterDriveProcess - dart-sdk/lib/async/future_impl.dart 721:7                                                                 <fn>
2023-09-28T15:17:42.7765270Z FlutterDriveProcess - dart-sdk/lib/async/zone.dart 1399:13                                                                      _rootRun
2023-09-28T15:17:42.7765950Z FlutterDriveProcess - dart-sdk/lib/async/zone.dart 1301:19                                                                      run
2023-09-28T15:17:42.7767110Z FlutterDriveProcess - dart-sdk/lib/async/zone.dart 1209:7                                                                       runGuarded
2023-09-28T15:17:42.7767780Z FlutterDriveProcess - dart-sdk/lib/async/zone.dart 1249:23                                                                      callback
2023-09-28T15:17:42.7768380Z FlutterDriveProcess - dart-sdk/lib/async/schedule_microtask.dart 40:11                                                          _microtaskLoop
2023-09-28T15:17:42.7769080Z FlutterDriveProcess - dart-sdk/lib/async/schedule_microtask.dart 49:5                                                           _startMicrotaskLoop
2023-09-28T15:17:42.7769720Z FlutterDriveProcess - dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                                        <fn>
2023-09-28T15:17:42.7770110Z FlutterDriveProcess - 
2023-09-28T15:17:42.7770490Z FlutterDriveProcess - The test description was:
2023-09-28T15:17:42.7771120Z FlutterDriveProcess -   can call services and service extensions
2023-09-28T15:17:42.7771780Z FlutterDriveProcess - ═════════════════════════════════════════════════════════════════
2023-09-28T15:17:42.7772150Z FlutterDriveProcess - 
2023-09-28T15:17:42.7772500Z FlutterDriveProcess - end of failure 1
2023-09-28T15:17:42.7772810Z FlutterDriveProcess - 
2023-09-28T15:17:42.7773090Z FlutterDriveProcess - 
2023-09-28T15:17:42.7773400Z FlutterDriveProcess - 
2023-09-28T15:17:42.8502390Z FlutterDriveProcess - Application finished.
2023-09-28T15:17:43.0059300Z Unhandled exception:
2023-09-28T15:17:43.0161280Z Exception: Test 'can call services and service extensions' failed: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
2023-09-28T15:17:43.0214060Z The following assertion was thrown running a test:
2023-09-28T15:17:43.0214870Z Assertion failed:
2023-09-28T15:17:43.0215600Z file:///Users/runner/work/devtools/devtools/packages/devtools_app/lib/src/shared/preferences.dart:335:12
2023-09-28T15:17:43.0216310Z _mainScriptDir != null
2023-09-28T15:17:43.0216920Z is not true
2023-09-28T15:17:43.0217380Z 
2023-09-28T15:17:43.0217810Z When the exception was thrown, this was the stack:
2023-09-28T15:17:43.0218870Z dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3                               throw_
2023-09-28T15:17:43.0219870Z dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3                                assertFailed
2023-09-28T15:17:43.0225530Z packages/devtools_app/src/shared/environment_parameters/environment_parameters_external.dart.js 72597:53  [_customPubRootStorageId]
2023-09-28T15:17:43.0226540Z packages/devtools_app/src/shared/environment_parameters/environment_parameters_external.dart.js 72552:82  [_persistCustomPubRootDirectoriesToStorage]
2023-09-28T15:17:43.0227470Z packages/devtools_app/src/shared/environment_parameters/environment_parameters_external.dart.js 72590:64  <fn>
2023-09-28T15:17:43.0229150Z dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                                        <fn>
2023-09-28T15:17:43.0230190Z dart-sdk/lib/async/zone.dart 1407:47                                                                      _rootRunUnary
2023-09-28T15:17:43.0231090Z dart-sdk/lib/async/zone.dart 1308:19                                                                      runUnary
2023-09-28T15:17:43.0232220Z dart-sdk/lib/async/future_impl.dart 162:18                                                                handleValue
2023-09-28T15:17:43.0235750Z dart-sdk/lib/async/future_impl.dart 846:44                                                                handleValueCallback
2023-09-28T15:17:43.0236720Z dart-sdk/lib/async/future_impl.dart 875:13                                                                _propagateToListeners
2023-09-28T15:17:43.0237670Z dart-sdk/lib/async/future_impl.dart 647:5                                                                 [_completeWithValue]
2023-09-28T15:17:43.0238610Z dart-sdk/lib/async/future_impl.dart 721:7                                                                 <fn>
2023-09-28T15:17:43.0239500Z dart-sdk/lib/async/zone.dart 1399:13                                                                      _rootRun
2023-09-28T15:17:43.0243630Z dart-sdk/lib/async/zone.dart 1301:19                                                                      run
2023-09-28T15:17:43.0244620Z dart-sdk/lib/async/zone.dart 1209:7                                                                       runGuarded
2023-09-28T15:17:43.0245930Z dart-sdk/lib/async/zone.dart 1249:23                                                                      callback
2023-09-28T15:17:43.0246960Z dart-sdk/lib/async/schedule_microtask.dart 40:11                                                          _microtaskLoop
2023-09-28T15:17:43.0247910Z dart-sdk/lib/async/schedule_microtask.dart 49:5                                                           _startMicrotaskLoop
2023-09-28T15:17:43.0249160Z dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                                        <fn>
2023-09-28T15:17:43.0249780Z 
2023-09-28T15:17:43.0250180Z The test description was:
2023-09-28T15:17:43.0250810Z   can call services and service extensions
2023-09-28T15:17:43.0251810Z ═════════════════════════════════════════════════════════════════
2023-09-28T15:17:43.0255900Z .
2023-09-28T15:17:43.0256360Z 
2023-09-28T15:17:43.0263270Z result {"result":"false","failureDetails":["{\"methodName\":\"can call services and service extensions\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following assertion was thrown running a test:\\nAssertion failed:\\nfile:///Users/runner/work/devtools/devtools/packages/devtools_app/lib/src/shared/preferences.dart:335:12\\n_mainScriptDir != null\\nis not true\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3                               throw_\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3                                assertFailed\\npackages/devtools_app/src/shared/environment_parameters/environment_parameters_external.dart.js 72597:53  [_customPubRootStorageId]\\npackages/devtools_app/src/shared/environment_parameters/environment_parameters_external.dart.js 72552:82  [_persistCustomPubRootDirectoriesToStorage]\\npackages/devtools_app/src/shared/environment_parameters/environment_parameters_external.dart.js 72590:64  <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                                        <fn>\\ndart-sdk/lib/async/zone.dart 1407:47                                                                      _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1308:19                                                                      runUnary\\ndart-sdk/lib/async/future_impl.dart 162:18                                                                handleValue\\ndart-sdk/lib/async/future_impl.dart 846:44                                                                handleValueCallback\\ndart-sdk/lib/async/future_impl.dart 875:13                                                                _propagateToListeners\\ndart-sdk/lib/async/future_impl.dart 647:5                                                                 [_completeWithValue]\\ndart-sdk/lib/async/future_impl.dart 721:7                                                                 <fn>\\ndart-sdk/lib/async/zone.dart 1399:13                                                                      _rootRun\\ndart-sdk/lib/async/zone.dart 1301:19                                                                      run\\ndart-sdk/lib/async/zone.dart 1209:7                                                                       runGuarded\\ndart-sdk/lib/async/zone.dart 1249:23                                                                      callback\\ndart-sdk/lib/async/schedule_microtask.dart 40:11                                                          _microtaskLoop\\ndart-sdk/lib/async/schedule_microtask.dart 49:5                                                           _startMicrotaskLoop\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                                        <fn>\\n\\nThe test description was:\\n  can call services and service extensions\\n═════════════════════════════════════════════════════════════════\\n\"}"]}
2023-09-28T15:17:43.0267560Z Failure Details:
2023-09-28T15:17:43.0268180Z Failure in method: can call services and service extensions
2023-09-28T15:17:43.0269020Z ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
2023-09-28T15:17:43.0269700Z The following assertion was thrown running a test:
2023-09-28T15:17:43.0270260Z Assertion failed:
2023-09-28T15:17:43.0271020Z file:///Users/runner/work/devtools/devtools/packages/devtools_app/lib/src/shared/preferences.dart:335:12
2023-09-28T15:17:43.0271740Z _mainScriptDir != null
2023-09-28T15:17:43.0272250Z is not true
2023-09-28T15:17:43.0272650Z 
2023-09-28T15:17:43.0273050Z When the exception was thrown, this was the stack:
2023-09-28T15:17:43.0273930Z dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3                               throw_
2023-09-28T15:17:43.0274860Z dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3                                assertFailed
2023-09-28T15:17:43.0275690Z packages/devtools_app/src/shared/environment_parameters/environment_parameters_external.dart.js 72597:53  [_customPubRootStorageId]
2023-09-28T15:17:43.0279690Z packages/devtools_app/src/shared/environment_parameters/environment_parameters_external.dart.js 72552:82  [_persistCustomPubRootDirectoriesToStorage]
2023-09-28T15:17:43.0280770Z packages/devtools_app/src/shared/environment_parameters/environment_parameters_external.dart.js 72590:64  <fn>
2023-09-28T15:17:43.0281760Z dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                                        <fn>
2023-09-28T15:17:43.0282690Z dart-sdk/lib/async/zone.dart 1407:47                                                                      _rootRunUnary
2023-09-28T15:17:43.0283570Z dart-sdk/lib/async/zone.dart 1308:19                                                                      runUnary
2023-09-28T15:17:43.0287890Z dart-sdk/lib/async/future_impl.dart 162:18                                                                handleValue
2023-09-28T15:17:43.0288980Z dart-sdk/lib/async/future_impl.dart 846:44                                                                handleValueCallback
2023-09-28T15:17:43.0290800Z dart-sdk/lib/async/future_impl.dart 875:13                                                                _propagateToListeners
2023-09-28T15:17:43.0291870Z dart-sdk/lib/async/future_impl.dart 647:5                                                                 [_completeWithValue]
2023-09-28T15:17:43.0292760Z dart-sdk/lib/async/future_impl.dart 721:7                                                                 <fn>
2023-09-28T15:17:43.0294280Z dart-sdk/lib/async/zone.dart 1399:13                                                                      _rootRun
2023-09-28T15:17:43.0298890Z dart-sdk/lib/async/zone.dart 1301:19                                                                      run
2023-09-28T15:17:43.0299780Z dart-sdk/lib/async/zone.dart 1209:7                                                                       runGuarded
2023-09-28T15:17:43.0300630Z dart-sdk/lib/async/zone.dart 1249:23                                                                      callback
2023-09-28T15:17:43.0301530Z dart-sdk/lib/async/schedule_microtask.dart 40:11                                                          _microtaskLoop
2023-09-28T15:17:43.0302450Z dart-sdk/lib/async/schedule_microtask.dart 49:5                                                           _startMicrotaskLoop
2023-09-28T15:17:43.0303560Z dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                                        <fn>
2023-09-28T15:17:43.0304070Z 
2023-09-28T15:17:43.0307720Z The test description was:
2023-09-28T15:17:43.0308420Z   can call services and service extensions
2023-09-28T15:17:43.0309340Z ═════════════════════════════════════════════════════════════════
2023-09-28T15:17:43.0309830Z 
2023-09-28T15:17:43.0310040Z 
2023-09-28T15:17:43.0310510Z #0      IntegrationTestRunner.run.runTest (package:devtools_shared/src/test/integration_test_runner.dart:139:11)
2023-09-28T15:17:43.0311200Z <asynchronous suspension>
2023-09-28T15:17:43.0311850Z #1      IntegrationTestRunner.run (package:devtools_shared/src/test/integration_test_runner.dart:144:5)
2023-09-28T15:17:43.0312590Z <asynchronous suspension>
2023-09-28T15:17:43.0313310Z #2      runFlutterIntegrationTest (file:///Users/runner/work/devtools/devtools/packages/devtools_app/integration_test/test_infra/run/run_test.dart:66:5)
2023-09-28T15:17:43.0313990Z <asynchronous suspension>
2023-09-28T15:17:43.0314660Z #3      _runTest (file:///Users/runner/work/devtools/devtools/packages/devtools_app/integration_test/run_tests.dart:46:3)
2023-09-28T15:17:43.0315300Z <asynchronous suspension>
2023-09-28T15:17:43.0315690Z #4      runOneOrManyTests (package:devtools_shared/src/test/integration_test_runner.dart:331:9)
2023-09-28T15:17:43.0319700Z <asynchronous suspension>
2023-09-28T15:17:43.0320410Z #5      main (file:///Users/runner/work/devtools/devtools/packages/devtools_app/integration_test/run_tests.dart:26:3)
2023-09-28T15:17:43.0321070Z <asynchronous suspension>
2023-09-28T15:17:43.3724700Z ##[error]Process completed with exit code 255.
2023-09-28T15:17:43.7383340Z ##[group]Run actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
2023-09-28T15:17:43.7383700Z with:
2023-09-28T15:17:43.7383950Z   name: golden_image_failures.integration_dart2js
2023-09-28T15:17:43.7384290Z   path: packages/devtools_app/integration_test/**/failures/*.png
```

**Comment by CoderDake** [comment]
I filed an issue for the test flake :)
https://github.com/flutter/devtools/issues/6492

**Comment by DanTup** [comment]
Thanks!

**Pull request merged**
