### PR TITLE
Don't fail at startup if textmate grammar can't be parsed by browser

### PR DESCRIPTION
**Pull request by DanTup**
The textmate grammar uses negative lookbehinds which are not supported in Safari. I've had a go at changing the grammar, but I can't find a way to support what we need (without a significant change to how the textmate grammar works) so for now this change will just handle errors and leave syntax highlighting disabled for browsers that don't support this.

Before this change, DevTools fails to load in safari:

image

With the change, it loads and prints a warning about the failed syntax highlighting in the console:

Screenshot 2022-12-13 at 12 40 16

And using the app works as normal:

Screenshot 2022-12-13 at 12 43 35

Fixes https://github.com/flutter/devtools/issues/2856.

### CODE REVIEW

**Review by elliette — APPROVED** [review]

**Comment by DanTup** [comment]
@elliette should I hold off landing this until bots are green, or is it likely they'll be this way for a while? (I'm less familiar with the process and current status here)

**Comment by elliette** [comment]
> @elliette should I hold off landing this until bots are green, or is it likely they'll be this way for a while? (I'm less familiar with the process and current status here)

@kenzieschmoll for input! I haven't done much devtools development recently

**Comment by kenzieschmoll** [comment]
I'm trying to fix the bots now - https://github.com/flutter/devtools/pull/4941. The breakage is due to the move to Dart version > 3.0.0, since a lot of the packages we depend on have an upper bound sdk constraint of 3.0.0.

**Comment by kenzieschmoll** [comment]
the temporary fix has landed (https://github.com/flutter/devtools/pull/4944). If you merge master, the bots should go green.

**Comment by DanTup** [comment]
Yep, all green. Thanks!

**Comment by DanTup** [comment]
@kenzieschmoll @CoderDake I realised I didn't add this to any changelog, and there doesn't seem to be a milestone for the next release. Assuming this should be noted (it makes DevTools load in Safari), is https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/framework/release_notes/release-notes-next.md the correct place to add it? (it looks like it, though there's nothing else currently listed there so I'm unsure if it's just a template).

**Comment by kenzieschmoll** [comment]
Yes, any notable user facing issues should be documented in the release-notes-next.md file. We automatically generate the CHANGELOG when we do the release, but the release notes should be drafted as we go.

**Comment by DanTup** [comment]
Thanks - I've opened https://github.com/flutter/devtools/pull/4966 to add this.

**Comment by wilmarques** [comment]
I was waiting for this so much!!!

When will it land?

**Pull request merged**
