### PR TITLE
Add some notes about configuring VS Code to run DevTools from local code

### PR DESCRIPTION
**Pull request by DanTup**
This adds some notes about running DevTools from local code in VS Code to test interactions with the server and embedded views.

It requires changes to the Dart extension that so far are only in the pre-release versions of the Dart extension (although I'd recommend any devs here use that version to help find any issues before they reach all users), v3.47:

Dart/Flutter pre-release versions

(note: although the screenshots shows both, there isn't currently a pre-release version of Flutter, the stable version is latest).

It would be useful to have someone other than me verify these steps work for them before landing (although be aware when testing this myself, I saw some [caching issues](https://github.com/flutter/devtools/issues/3896) that might complicated that).

### CODE REVIEW

**Review by kenzieschmoll — COMMENTED** [review]
When I did this, my VS Code seems to be stuck on this:
Screen Shot 2022-08-08 at 2 37 59 PM

**Comment by DanTup** [comment]
@kenzieschmoll how long did you wait? It could take a little while for the build to complete (however long `build_e2e.dart` usually takes on your machine).

You can enabling logging by adding this to your _Workspace_ Settings (`F1` -> `Preferences: Open Workspace Settings (JSON)`) and reload (`F1` -> `Developer: Reload Window`) and then open the log file, which should show the output from the script as it runs.

```js
"dart.devToolsLogFile": "logs/devtools.txt"
```

(I presume you're on a recent DevTools and SDK checkout that include my changes from last week?)

**Comment by DanTup** [comment]
I just noticed there's an existing "Developing with VS Code -> DevTools Server" section in this file, although I think it might be out of date (it says to run `packages/devtools/bin/devtools`). Should that section just be replaced by this new text? (I don't think there's a way to run with the server now without having the SDK?)

**Comment by kenzieschmoll** [comment]
Yes anything that references `bin/devtools.dart` is obsolete. It could be work checking if the the `--debug` flag can still be passed to the server, though I personally haven't used that workflow in quite a while (year(s)?).

**Comment by kenzieschmoll** [comment]
I upgraded to the latest Dart SDK with your changes and retried - it works now 👍 LGTM!

**Review by kenzieschmoll — APPROVED** [review]

**Comment by DanTup** [comment]
> Yes anything that references `bin/devtools.dart` is obsolete.

Ok, shall I remove that section entirely, or there is still some value in having instructions for running the server manually without going through the VS Code integration?

> It could be work checking if the the `--debug` flag can still be passed to the server, though I personally haven't used that workflow in quite a while (year(s)?).

That flag still exists in the DDS server script, but as far as I can see the _only_ thing it does is wraps `bold()` around a message:

```dart
if (!machineMode && debugMode) {
  // Add bold to help find the correct url to open.
  message = ConsoleUtils.bold('$message\n');
}
```

I can't see any other use of it.

**Comment by kenzieschmoll** [comment]
> Ok, shall I remove that section entirely, or there is still some value in having instructions for running the server manually without going through the VS Code integration?

Yeah, there is value in this. The instruction there should be simple - just running the e2e script locally.

**Comment by DanTup** [comment]
It looks like there are some more things that need updating in that area.. the launch config (in `.vscode/launch.json`) is also trying to use old scripts that no longer exist.

If you're happy for me to land this change as-is, I'll go through that stuff and update it all for another PR.

**Review by kenzieschmoll — APPROVED** [review]
Good to land and the other stuff can be cleaned up in a follow up

**Pull request merged**
