### PR TITLE
Add selection styling to Logs table

### PR DESCRIPTION
**Pull request by kenzieschmoll**
Screen Shot 2020-11-03 at 2 14 36 PM

Addresses part of https://github.com/flutter/devtools/issues/1982

### CODE REVIEW

**Comment by devoncarew** [comment]
For the dark theme, the selection background color looks pretty high contrast. Is this a std background selection color for material? Should we be customizing it for our tables? A darker row color may work better.

**Comment by kenzieschmoll** [comment]
This is the selection color UXD recommended and is used in other parts of DevTools to indicate selection (e.g. timeline, debugger (see https://github.com/flutter/devtools/issues/1982#issuecomment-643471410))

**Comment by devoncarew** [comment]
> This is the selection color UXD recommended and is used in other parts of DevTools to indicate selection (e.g. timeline, debugger (see [#1982 (comment)](https://github.com/flutter/devtools/issues/1982#issuecomment-643471410)))

Ah, ok then.

**Review by devoncarew — APPROVED** [review]

**Comment by kenzieschmoll** [comment]
>>This is the selection color UXD recommended and is used in other parts of DevTools to indicate selection (e.g. timeline, debugger (see #1982 (comment)))

>Ah, ok then.

However, would not be opposed to revisiting this color in a future polish task - it does seem kind of intense in some places.

**Pull request merged**
