### PR TITLE
Fix issue where socket profile data was being displayed as web socket connections

### PR DESCRIPTION
**Pull request by bkonyi**
Socket data is now displayed correctly, with method set to `SOCKET` and type displaying the socket type (e.g., `TCP` vs `UDP`).

Fixes https://github.com/flutter/devtools/issues/3033

image

### CODE REVIEW

**Comment by kenzieschmoll** [comment]
Please add release notes for this change with a screenshot (preferably a smaller one than is in the PR description since this will be shown in DevTools release notes).

Also, can you change the "Uri" column to "address" instead? I think that would better encompass both Socket traffic and Http traffic.

**Review by kenzieschmoll — APPROVED** [review]
LGTM once tests pass!

**Comment by laterdayi** [comment]
Thanks for your help, how should I update, can't wait to use this feature

**Comment by bkonyi** [comment]
> Thanks for your help, how should I update, can't wait to use this feature

Right now you'll need to be using the Flutter main branch on a commit that includes the updated Dart SDK. The changes might not have rolled all the way to Flutter yet, so your safest bet is to wait for the next beta release which includes these changes which will hopefully happen in the next week or two.

**Pull request merged**
