### PR TITLE
Color stack frames by categories: native, dart core, flutter core

### PR DESCRIPTION
**Pull request by kenzieschmoll**
Fixes https://github.com/flutter/devtools/issues/578

Screen Shot 2021-08-27 at 10 57 42 AM
Screen Shot 2021-08-27 at 10 52 55 AM
Note: user code and code from outside of native and dart/flutter core
Screen Shot 2021-08-27 at 10 57 05 AM
Light theme:
Screen Shot 2021-08-27 at 10 58 02 AM

@InMatrix any UX input on colors? I grabbed the flutter color and the color for the "other" category from the flutter brand guidelines deck.

### CODE REVIEW

**Comment by echo27713** [comment]
> Addressed review comments, added a prefix to tooltips, and more details to the legend that should clarify some of the raised questions:
> Screen Shot 2021-08-27 at 1 34 14 PM
> Screen Shot 2021-08-27 at 1 57 48 PM

Thanks Kenzie for addressing my questions. It looks clearer!

Based on the user study results, users may want to focus on their own app code. So we can consider to assign more prominent color to 'App code' and make other categories's color scheme with muted colors. 

Szu can definitely give some color suggestions.

**Comment by ayanogawa** [comment]
@kenzieschmoll 
Some color contrast feedback to make the UI more accessible for colorblind and low vision users. Please feel free to reach out if there's any questions. Thank you.

Dark theme
App code: Google Orange 300 (#FCAD70)
Native code: #72B6C6 Google Cyan 200 (#A1E4F2)
Dart core libraries: #6887F7
Flutter framework: #928EF9
Text color: Google Grey 900 (#202124)
Timeline divider: #Google Grey 700 (#5F368)

Light theme
App code: #CA432B
Native code: Google Cyan 900 (#007B83)
Dart core libraries: #1D649C
Flutter framework: #6864D3
Text color: Google Grey 50 (#F8F9FA)
Timeline divider: #Google Grey 300 (#DADCE0)

**Comment by kenzieschmoll** [comment]
@ayanogawa Thanks for the color sugestions! I like how this looks in the dark theme:
Screen Shot 2021-08-30 at 3 29 01 PM

but I think the red looks a little too jarring for the light theme. Red to me would communicate that these frames are the problem within the profile, when really what we want to communicate is that "this code may be more relevant to you". Do you have an idea for another color that doesn't make a user jump to the thoughts of to "error" or "hot spot"?
Screen Shot 2021-08-30 at 3 29 09 PM

**Comment by ayanogawa** [comment]
Thanks for the call out, Kenzie. Yes. It makes sense. We can also try Google Orange 500 (#FA7B17) and keep the black text.

**Comment by kenzieschmoll** [comment]
Google Orange 500:
Screen Shot 2021-08-31 at 7 32 19 AM

**Comment by ayanogawa** [comment]
That's awesome. Thank you for making the tool accessible!

**Pull request merged**
