### PR TITLE
Temporarily disable the provider screen.

### PR DESCRIPTION
**Pull request by terrylucas**

### CODE REVIEW

**Comment by kenzieschmoll** [comment]
We can't import `freezed_annotation` because we don't want that package in google3. Let's disable the provider screen and figure out a way around that for the next milestone. That was the original plan, so we may need to dig a bit more to make sure this dep is not necessary.

**Comment by kenzieschmoll** [comment]
LGTM on pub_publish.sh changes

**Comment by terrylucas** [comment]
Okay removed the dependency and temporarily disabled the provider screen.

**Review by kenzieschmoll — APPROVED** [review]

**Review by jacob314 — APPROVED** [review]
lgtm

**Pull request merged**
