### PR TITLE
address new lint results

### PR DESCRIPTION
**Pull request by devoncarew**
- address some new lint results (when using the Dart SDK compiled from head)

### CODE REVIEW

**Comment by devoncarew** [comment]
From the merge to master, it looks like the `executeWithDelay` test is flaky:

```
00:29 +70 -1: test\utils_test.dart: utils executeWithDelay [E]
  Expected: a value less than <200>
    Actual: <442>
     Which: is not a value less than <200>
  
  package:test_api                    expect
  ..\null\test\utils_test.dart 96:7   <fn>
  ===== asynchronous gap ===========================
  dart:sdk_internal                   _async
  ..\null\test\utils_test.dart 68:30  <fn>
```

**Comment by terrylucas** [comment]
Noticed that integration tests prints out the JSON (e.g.,
_sendNotification) removing those prints causes timing problems with the
integration tests. These prints show up in the console during normal
DevTools runs and shouldn't, but removing the prints causes timing
problems. If the prints are necessary it should be a test only function not
executed normally.  Added a TODO but will file an issue on this too.

**Comment by terrylucas** [comment]
Forgot to say these tests were also flakey.

**Comment by terrylucas** [comment]
https://github.com/flutter/devtools/issues/774

**Pull request merged**
