### PR TITLE
Improvements to performance tooling from UXR

### PR DESCRIPTION
**Pull request by kenzieschmoll**
Addresses part of https://github.com/flutter/devtools/issues/2497:
- [x] move performance tab next to timeline tab
- [x] rename "event details" to CPU profiler on timeline page
- [x] rename performance page to "CPU profiler"
- [x] move bottom up profiler tab to position 0

### CODE REVIEW

**Review by jacob314 — APPROVED** [review]
lgtm

**Review by jacob314 — COMMENTED** [review]
Fyi @DanTup in case you are directly launching links to the timeline page from vscode.

**Comment by DanTup** [comment]
> Fyi @DanTup in case you are directly launching links to the timeline page from vscode.

I am, thanks! I'll need to handle this based on the version. The current live version is 0.9.5+1. Is it safe for me to assume that >= 0.9.6 would include this, and anything < 0.9.5+1 should use the old URLs?

**Comment by kenzieschmoll** [comment]
yes that is correct. See also https://github.com/flutter/devtools/pull/2563, which renames timeline to performance. so >= 0.9.6

"timeline" --> "performance"
"performance" --> "cpu-profiler"

**Comment by DanTup** [comment]
Got it! I've got a fix ready to ship in a patch, though I'm a little worried about caching causing issues - I added some notes here:

https://github.com/flutter/devtools/issues/1674#issuecomment-754609493

If users see the same thing I did, they might end up getting errors because the old JS still loads and we use the new page IDs.

**Comment by DanTup** [comment]
I've published a new Dart-Code with the new page IDs (selected based on the version). I'll send a PR that removes the service worker here shortly.

If you let me know when DevTools is released, I'll re-test using the published version. Thanks!

**Pull request merged**
