### PR TITLE
app_shared: migrate to pkg:web

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Review by kenzieschmoll — COMMENTED** [review]
can you add a changelog entry to devtools_app_shared under 0.0.7? thanks

**Comment by kevmoo** [comment]
> can you add a changelog entry to devtools_app_shared under 0.0.7? thanks

Done!

**Comment by kevmoo** [comment]
@kenzieschmoll – PTAL!

**Review by kenzieschmoll — APPROVED** [review]

**Comment by kenzieschmoll** [comment]
If you merge master, this should go green and we can land this change.

**Comment by kevmoo** [comment]
This is now subsumed by https://github.com/flutter/devtools/pull/6626/

**Pull request closed without merging**
