### PR TITLE
Change "dart.bat" to "dart" for running VM on Windows

### PR DESCRIPTION
**Pull request by DanTup**
@DaveShuckerow I'm not sure what the intention was here, but Dart is an exe on Windows (only `pub` and `flutter` are batch files). The bots fail running this, so this restores it.

~If there was a deliberate reason not to use `Platform.resolvedExecutable` and instead `dart` from `PATH` then this may need tweaking to just be `dart` (and if so we should probably add some comments about why).~

Apparently this is required - though I'm not sure why. Any ideas? It'd be good to comment it (or if it's a bug, try and get it fixed).

### CODE REVIEW

**Comment by DanTup** [comment]
Ok, I guess there was some reason! Using `Platform.resolvedExecutable fails with:

```
 STDERR: [ERROR:flutter/shell/common/engine.cc(188)] Could not prepare to run the isolate.
  test/integration_tests/server_test.dart 57:36  main.<fn>.<fn>
```

I'll try changing it to use `dart`, though it's not clear why that would behave differently.

**Comment by DanTup** [comment]
It does, though I'd like to understand this change before landing it. Hoping @DaveShuckerow might have some idea. It seems strange that this change actually changes anything (except by possibly accidentally using Dart from the Dart SDK instead of Flutters, but that sounds like a weird quirk we should at least document in comments).

**Comment by DaveShuckerow** [comment]
> Hoping @DaveShuckerow might have some idea. It seems strange that this change actually changes anything (except by possibly accidentally using Dart from the Dart SDK instead of Flutters, but that sounds like a weird quirk we should at least document in comments).

The resolved executable in a Flutter test is the flutter_tester binary, not Dart.

`flutter pub run test` might give us a resolved executable of Dart.

**Comment by DanTup** [comment]
> The resolved executable in a Flutter test is the flutter_tester binary, not Dart.

Ah, that makes sense. Do we plan to change to `flutter run`? Should I land this, or should we try that? (my only worry with this is that if the CI builds have both Dart and Flutter SDKs, if the PATH is wrong we might end up mismatching versions here that could cause confusion).

(I'm heading out now - but feel free to land this if you think it's the best fix for now).

**Comment by DanTup** [comment]
I'll land this to fix the Windows tests for now, but if we switch to `flutter run`, we should consider changing back to `Platform. resolvedExecutable` to avoid crossing Dart versions.

**Pull request merged**
