### PR TITLE
Add DevTools section to Flutter sidebar

### PR DESCRIPTION
**Pull request by kenzieschmoll**
Screenshot 2024-04-16 at 12 42 22 PM

Fixes https://github.com/flutter/devtools/issues/7165
Fixes https://github.com/flutter/devtools/issues/7595

@DanTup 

TODO before submitting - fix tests.

### CODE REVIEW

**Comment by polina-c** [comment]
Can you add documentation that would explain how to make extension to appear on the sidebar, somewhere?

**Comment by kenzieschmoll** [comment]
> Can you add documentation that would explain how to make extension to appear on the sidebar, somewhere?

This change is not for DevTools extensions. That part will be added once static extension support is available.

**Review by bkonyi — APPROVED** [review]

**Comment by kenzieschmoll** [comment]
@DanTup merging to unblock the next change I'm preparing. I will address any comments you have in a follow up PR. I did test the change we discussed to make `debugSessionId` nullable, and it did work as intended.

**Review by DanTup — COMMENTED** [review]
LGTM!

> I did test the change we discussed to make `debugSessionId` nullable, and it did work as intended.

Great! I've updated the types in https://github.com/Dart-Code/Dart-Code/commit/04dbe4eadbaa89be2ba4d0286a2f7250ea8db848 to make this explicit there (it won't change behaviour, but makes it clearer this is intended).

**Pull request merged**
