### PR TITLE
Use latest pkg:vm_service

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
Why not allow a range of versions?

**Comment by kevmoo** [comment]
Feel free to squash/merge and delete the branch if you're happy

**Comment by kevmoo** [comment]
> LGTM, although the 1.0.0+1 release was solely to update the README on pub.

I have some tools that track if a package has outdated dependencies. This makes the tool happy 😄

**Comment by bkonyi** [comment]
> > LGTM, although the 1.0.0+1 release was solely to update the README on pub.
> 
> I have some tools that track if a package has outdated dependencies. This makes the tool happy 😄

Haha, fair enough!

**Pull request merged**
