### PR TITLE
Revert "update to use build_runner test for precompiled tests (#633)"

### PR DESCRIPTION
**Pull request by jacob314**
This reverts commit b720f26147080797891fe1d955b134a98e177a1a.

### CODE REVIEW

**Comment by DanTup** [comment]
Whoops, I forgot by pushing to your PR it would break CLA-bot 😞

Still, I'll try and make this PR green, and you can land it in the morning - I don't think there's any urgent need to have it green before the US wakes up.

**Comment by DanTup** [comment]
I'm not sure what's going on here, so I'm gonna leave this till you're back:

```
01:04 +19: test/inspector_controller_test.dart: inspector controller tests initial state
Unrecognized error: Bad state: StreamSink is closed
Unrecognized error: Bad state: StreamSink is closed
Unrecognized error: Bad state: StreamSink is closed
Unrecognized error: Bad state: StreamSink is closed
Unrecognized error: Bad state: StreamSink is closed
Unrecognized error: Bad state: StreamSink is closed
Bad state: StreamSink is closed
Bad state: StreamSink is closed
01:04 +18 -1: test/inspector_controller_test.dart: inspector controller tests (tearDownAll)
01:05 +18 -1: test/inspector_controller_test.dart: inspector controller tests initial state [E]
  Bad state: StreamSink is closed
  dart:async                                                    _Completer.completeError
  package:devtools/src/eval_on_dart_library.dart 208:20         EvalOnDartLibrary.addRequest.wrappedRequest
  ===== asynchronous gap ===========================
  dart:async                                                    _asyncErrorWrapperHelper
  package:devtools/src/eval_on_dart_library.dart                EvalOnDartLibrary.addRequest.wrappedRequest
  package:devtools/src/eval_on_dart_library.dart 232:21         EvalOnDartLibrary.addRequest
  ===== asynchronous gap ===========================
  dart:async                                                    _asyncErrorWrapperHelper
  package:devtools/src/eval_on_dart_library.dart                EvalOnDartLibrary.addRequest
  package:devtools/src/inspector/inspector_service.dart 441:29  ObjectGroup._callServiceExtension
  package:devtools/src/inspector/inspector_service.dart 461:12  ObjectGroup.invokeServiceMethodDaemonParams
  package:devtools/src/inspector/inspector_service.dart 432:12  ObjectGroup.invokeServiceMethodDaemonArg
  package:devtools/src/inspector/inspector_service.dart 466:12  ObjectGroup.invokeServiceMethodDaemonInspectorRef
  package:devtools/src/inspector/inspector_service.dart 660:11  ObjectGroup.invokeServiceMethodReturningNodeInspectorRef
  package:devtools/src/inspector/inspector_service.dart 754:30  ObjectGroup.getSelection
  ===== asynchronous gap ===========================
  dart:async                                                    _StreamImpl.listen
  package:devtools/src/inspector/inspector_service.dart 49:28   new InspectorService
  package:devtools/src/inspector/inspector_service.dart 103:12  InspectorService.create
```

**Comment by jakemac53** [comment]
what is the reason for the revert?

**Comment by DanTup** [comment]
@jakemac53 it broke some of the tests (I'm not sure why yet, I don't know if it's a timing issue, didn't get to digging yet):

https://travis-ci.org/flutter/devtools/builds/527055260?utm_source=github_status&utm_medium=notification

**Comment by jakemac53** [comment]
Note that those are not the `pub run build_runner ...` tests that are failing... those are the unchanged `pub run test ...` tests.

They also pass for me locally which is weird.

**Comment by jakemac53** [comment]
I think maybe this is actually due to the update to expand the `build_web_compilers` version?

**Comment by DanTup** [comment]
@jakemac53 I had a go at er-merging this locally to see if I could repro, but everything passes. Is there anything I might need to do to ensure things are running the same way as they did on Travis? (I don't fully understand the change you described above, so not sure what might affect this).

**Pull request merged**
