### PR TITLE
Update to latest textmate grammar + support patterns in captures in parser

### PR DESCRIPTION
**Pull request by DanTup**
@bkonyi This updates to the [latest grammar](https://github.com/dart-lang/dart-syntax-highlight/blob/master/grammars/dart.json), which includes a few fixes and better highlighting for interpolated strings.

Before:

Screenshot 2022-07-27 at 16 56 09

After:

Screenshot 2022-07-27 at 16 47 27

However, the parser did not support having patterns nested in captures so I also had to make some changes there. I extracted a `PatternMatcher` that matches anything that has a set of `patterns` (and added this to `_Matcher.parse()`). and now specifically look for nested patterns in captures.

With these changes, I get the same output when running some tests (see https://github.com/dart-lang/dart-syntax-highlight/pull/28) as a NodeJS tool I was using to do the same. I have found some issues with the grammar (such has handling of nested type args), but I'd like to get and get some tests for the grammar (via https://github.com/dart-lang/dart-syntax-highlight/pull/28) before I start trying to fix that, to ensure I don't regress anything while trying to fix (since I don't expect the fix to be trivial).

Please review carefully, I'm a parser noob :-)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by bkonyi — APPROVED** [review]
It's been awhile since I've looked at the parser code, but I've looked through this a couple of times and I don't see anything obviously wrong, so LGTM.

**Comment by DanTup** [comment]
I've pushed updates to the span parser tests for latest changes, although I've found a few other differences with the NPM tool I ran that I haven't tracked down yet, so I'm going to try and get to the bottom of them before landing this (in case they're issues introduced by this change).

**Comment by kenzieschmoll** [comment]
Is this PR still blocked or is it ready to land?

**Comment by DanTup** [comment]
This isn't good to go yet. There are a few other issues with the parser I want to address before trying to upgrade to the latest grammar (which includes these additional things we don't handle). I'll close this and file a new PR when I'm ready to upgrade.

**Pull request closed without merging**
