### PR TITLE
Send pageReady event to dwds from Inspector page

### PR DESCRIPTION
**Pull request by annagrin**
Send `pageReady` event from the Inspector page, similar to what is already
done from the Debugger page.

Closes: https://github.com/flutter/devtools/issues/3711

### CODE REVIEW

**Comment by kenzieschmoll** [comment]
A couple comments here:
1) the linked issue looks like we want to measure the time it takes to start the inspector, but we aren't measuring anything in the DevTools analytics for that metric in this PR - only sending a dwds event. We should probably do both, just like we do for the debugger.
2) Do we want to measure the time until the widget tree is loaded or time until the inspector screen is displayed? I think we should measure time it takes until the widget tree is displayed, because the inspector screen without the widget tree is not useful for users. Right now the event is being sent from a value listenable builder related to the toggle select widget mode button, so we'll want to send the event in a different spot. I'm looking currently for the best place to do this.
3) Does it matter if the DWDS event is sent more than once? What if the event is sent from the Inspector, and then the user goes to the Debugger page, which sends another dwds pageReady event. Should we guard against this?

**Comment by kenzieschmoll** [comment]
After digging a little, I think this may be the best place to mark end of startup time or "pageReady": at the end of this if block https://github.com/flutter/devtools/blob/ecba4cd9dbdbe2e15ec0d299d24b8f23d9a151ab/packages/devtools_app/lib/src/screens/inspector/inspector_controller.dart#L414. 

@jacob314 what do you think?

**Comment by annagrin** [comment]
> A couple comments here:
> 
> 1. the linked issue looks like we want to measure the time it takes to start the inspector, but we aren't measuring anything in the DevTools analytics for that metric in this PR - only sending a dwds event. We should probably do both, just like we do for the debugger.

The time measurement you are suggesting is done for DevTools analytics, which is separate from dwds analytics. For the purpose of the bug fix it is not needed, but please let me know if you would like me to add this as well. Dwds tracks time starting from the user clicking on the dart extension button, and ending with any page ready event from the DevTools, and it already has the logic to record the IPL event just once.

> 2. Do we want to measure the time until the widget tree is loaded or time until the inspector screen is displayed? I think we should measure time it takes until the widget tree is displayed, because the inspector screen without the widget tree is not useful for users. Right now the event is being sent from a value listenable builder related to the toggle select widget mode button, so we'll want to send the event in a different spot. I'm looking currently for the best place to do this.

We are measuring the time  it takes for the DevTools to be available to the user after the user initiated the debugging session. Not sure what is the best way to define it - I think it is ok not to include some heavy asynchronous operations in that, if the user can already do something. I think there is a lot of expression evaluation happening for the inspector tabs that we probably don't want to consider a part of "IPL time". If we just want to measure the time until time until the inspector screen is displayed, is the event sent in the correct spot?

> 3. Does it matter if the DWDS event is sent more than once? What if the event is sent from the Inspector, and then the user goes to the Debugger page, which sends another dwds pageReady event. Should we guard against this?

It is ok to send the event many times, dwds will ignore all such events after the first `pageReady` coming from either debugger  or inspector.

**Comment by kenzieschmoll** [comment]
> For the purpose of the bug fix it is not needed, but please let me know if you would like me to add this as well.

We can leave it out of this PR then, but would you mind filing an issue and adding a TODO in the code that links to it? Thanks.

> I think it is ok not to include some heavy asynchronous operations in that, if the user can already do something. I think there is a lot of expression evaluation happening for the inspector tabs that we probably don't want to consider a part of "IPL time". 

[1] I think we have gotten complaints in the past that the widget tree is slow to load in g3, and I think slow to load for flutter web specifically. I'll defer to your judgement on what you are interested in measuring for DWDS, but for the devtools analytics we will add, we'll probably end the timer when the widget tree loads. 

> If we just want to measure the time until the inspector screen is displayed, is the event sent in the correct spot?

I think there may be a better place to put this event. As for where to put the event, it will depend on your response to [1] above.

**Comment by annagrin** [comment]
@kenzieschmoll 

> We can leave it out of this PR then, but would you mind filing an issue and adding a TODO in the code that links to it? Thanks.

Sure, will do. Opened a separate bug for DevTools analytics:  https://github.com/flutter/devtools/issues/3879

> [1] I think we have gotten complaints in the past that the widget tree is slow to load in g3, and I think slow to load for flutter web specifically. I'll defer to your judgement on what you are interested in measuring for DWDS, but for the devtools analytics we will add, we'll probably end the timer when the widget tree loads.

I'll measure the whole time until the widget tree is loaded as well, as we discussed offline.

**Review by kenzieschmoll — APPROVED** [review]

**Comment by kenzieschmoll** [comment]
Do we also want to add an event somewhere in the isolate connection code that would be triggered at the same time for any devtools launch (independent of whether the first page is the inspector or the debugger)?

**Pull request merged**
