### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by tomgilder**

### CODE REVIEW

**Comment by tomgilder** [comment]
I signed it :-)

**Comment by DanTup** [comment]
@tomgilder Is the email address you signed it with different to the one on the commit? (You can see the email on the commit by running `git log` - it's tom.gilder @ some company domain).

**Comment by jacob314** [comment]
@tomgilder let me know if you need any help fixing @DanTup's suggestion. I had the same issue the first time I committed a change to the flutter repo. I think I fixed it by making sure my username was correct locally and then cherry-picking my own commit but this is git so there are probably 10 different ways to fix the issue.

**Comment by DanTup** [comment]
Since this message is user-facing, I've fixed the typo in #505. Thanks for spotting it, and I'm sure we can resolve your CLA issues if you make another PR. Thanks!

**Pull request closed without merging**
