### PR TITLE
Move everything under packages/devtools while nobody has any major pending commits.

### PR DESCRIPTION
**Pull request by jacob314**
This will let us move the fixtures into a separate
fixtures directory which makes pub publish happier
and is a bit cleaner as there will be less non-devtools code under package:devtools.

### CODE REVIEW

**Comment by jacob314** [comment]
One more move. Next step is to move the fixture code around but no rush on that as moving it is much less likely to cause someone to waste time on git merge conflicts.

**Comment by jacob314** [comment]
I think the line change diff is a lie. This CL should just be all moves.

**Comment by DanTup** [comment]
LGTM, though GH shows everything as renames except a few files as deleted (eg. `test/fixtures/flutter_app/ios/ServiceDefinitions.json`) without an equiv create - I don't know if that's intended?

We'll also probably want to move the `.vscode` folder with it (I'm assuming working in VS Code we'll either open the packages/devtools folder, or add it as a workspace folder, though if we think we'll most likely open the root and not have many packages, we could just update the paths in it).

**Comment by jacob314** [comment]
Given the tests pass I think the missing files are files that were in the .gitignore that had been accidentally checked in. Let me move the .vscode folder.

**Comment by devoncarew** [comment]
> This will let us move the fixtures into a separate
fixtures directory which makes pub publish happier

Makes sense -

Re: `packages/devtools` - do we expect other packages here? If no we could go with a slightly flatter directory structure - just `//devtools/`. Happy either way though.

**Comment by jacob314** [comment]
I think each of the fixture applications is technically its own package albeit an unpublished one but I don't feel strongly. My main bias was just in case we want other true packages and to keep the directory from looking like
~/git/devtools/devtools on my local machine which I find more confusing than ~/git/devtools/packages/devtools
Another package I imagine adding in the future is:
packages/devtools_database
which is a server application talking vm service protocol that stores a database tracking memory usage info.

**Pull request merged**
