### PR TITLE
Memory legends renaming

### PR DESCRIPTION
**Pull request by alexlindroos**
@terrylucas 

New PR from #2806

Screenshot 2021-03-24 at 10 10 34
Screenshot 2021-03-24 at 10 10 22
Screenshot 2021-03-24 at 10 10 10
Screenshot 2021-03-24 at 10 09 56

### CODE REVIEW

**Comment by kenzieschmoll** [comment]
DBC: the legend is getting cutoff - the width of that overlay will need to be increased to fit all the content

**Comment by alexlindroos** [comment]
> DBC: the legend is getting cutoff - the width of that overlay will need to be increased to fit all the content

Hi @kenzieschmoll, you mean adding padding to the right of the overlay? 
Is this the cutoff you are mentioning?

Screenshot 2021-03-25 at 12 03 39

**Comment by terrylucas** [comment]
> > DBC: the legend is getting cutoff - the width of that overlay will need to be increased to fit all the content
> 
> Hi @kenzieschmoll, you mean adding padding to the right of the overlay?
> Is this the cutoff you are mentioning?
> 
> Screenshot 2021-03-25 at 12 03 39

Yes, shortening the name should have fixed it automatically.  Before the name was too long.

Does this screenshot match the code in the PR?

**Comment by alexlindroos** [comment]
> > > DBC: the legend is getting cutoff - the width of that overlay will need to be increased to fit all the content
> > 
> > 
> > Hi @kenzieschmoll, you mean adding padding to the right of the overlay?
> > Is this the cutoff you are mentioning?
> > Screenshot 2021-03-25 at 12 03 39
> 
> Yes, shortening the name should have fixed it automatically. Before the name was too long.
> 
> Does this screenshot match the code in the PR?
> If so, then I'll check it in and I'll update the goldens.

Not yet, I just made sure this cutoff was happening, because the padding. I will push this screenshot changes to padding.

**Comment by alexlindroos** [comment]
Now the right padding in legends container is included in the PR and it is the way in the screenshot.

**Pull request merged**
