### PR TITLE
Don't double-build pull requests

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
Feel free to squash/merge and delete the branch if you're happy

**Comment by kevmoo** [comment]
Thoughts @bkonyi ?

**Comment by DanTup** [comment]
Out of interest - when do you see double-builds without this? I removed this in https://github.com/flutter/devtools/pull/398 because my understanding was that it would only cause extra builds if you were creating branches here in this repo (but we mostly run on our own forks).

(I removed it because when testing/troubleshooting on Travis, this prevents it from running on my own fork/branch, so I have to keep removing it temporarily).

**Comment by kevmoo** [comment]
If folks generally don't send PRs from branches on this repo, that makes
sense.

**Comment by DanTup** [comment]
I don't *think* it's common, but I don't do most of the work here :) It's also not super common that I'm running on my fork (it's just usually when I'm debugging CI/Travis issues and don't want to have to spam a live PR) so it's only minor inconvenience.

I don't know what triggered this PR - if removing it is likely to cause inconvenience for others, I'll just remove it temporarily when I need to. If it was added mainly because it seemed like there was no downside (but the inconvenience of not having it was minor), then I wouldn't mind taking it out next time I need to debug Travis again.

**Pull request merged**
