### PR TITLE
Add a build.yaml to disable dart2js optimisation

### PR DESCRIPTION
**Pull request by DanTup**
This is the file I had to create to change this when testing locally. I think it's worth committing to have  better stack traces in the pre-built version while it's in development/preview?

### CODE REVIEW

**Comment by DanTup** [comment]
Oh, I'm a little confused... That's the same issue mentioned in #193 which only occurs with the dart2js build but not ddc one. I expected this file only to change the optimisations used for dart2js/release builds, but it seems like it may also be changing whatever the tests were doing to use dart2js?

I'll do some more testing - maybe if I just remove the dart2jd part here (leaving the args) it won't do that.

That said, it would also be beneficial to run the tests using the version we're going to ship - though maybe we should do it deliberately in the test scripts rather than making them all change (since presumably this will affect local dev too?).

**Comment by devoncarew** [comment]
I did some investigation into the splitter js issue but made no real progress :(

It does look like we're loading the script properly, but we're not able to invoke the JS symbol. Perhaps dart2js thinks the symbol has been renamed?

> That said, it would also be beneficial to run the tests using the version we're going to ship - though maybe we should do it deliberately in the test scripts rather than making them all change (since presumably this will affect local dev too?).

This is a great idea - we should have a 2nd set of bots that compile and run the tests using dart2js. I'll open an issue for that.

**Comment by devoncarew** [comment]
Hmm, I tried creating a PR against this PR, but just ended up deleting the `compiler:` line in a new commit: https://github.com/flutter/devtools/pull/196/commits/b39ef671e9af2caf8e9876b4d6d648e7b24021dc

**Comment by DanTup** [comment]
Well, I guess the effect is the same :)

Looks like the build is green, so I presume that it did what we wanted (stopped forcing the tests to use dart2js). Do you know if it still honours the optimisation setting when building in release mode? (I can check this tomorrow if not).

**Comment by devoncarew** [comment]
> Do you know if it still honours the optimisation setting when building in release mode?

I think it does, but haven't checked.

**Pull request merged**
