### PR TITLE
Verify that benchmark tests meet expected performance thresholds

### PR DESCRIPTION
**Pull request by kenzieschmoll**
Fixes https://github.com/flutter/devtools/issues/8583

### CODE REVIEW

**Comment by nandnai-gurjar** [comment]
hello

**Review by elliette — APPROVED** [review]

**Comment by kenzieschmoll** [comment]
The WASM results are running much slower on the bots than locally. Locally, the benchmark tests pass and meet the expected thresholds, which are set to 16666 micros (16.6 ms is what is required for performant rendering on a 60 FPS device). On the CI the test is failing:
```
  [WASM Benchmarks] The following benchmark scores exceeded their expected thresholds:
  
  [devtools_offlineCpuProfilerScreen.wasm] flutter_frame.total_time.average was 35744.85030395137 μs, which exceeded the expected threshold, 16666.0 μs.
  [devtools_offlineCpuProfilerScreen.wasm] flutter_frame.total_time.p50 was 54035.0 μs, which exceeded the expected threshold, 16666.0 μs.
  [devtools_offlineCpuProfilerScreen.wasm] flutter_frame.total_time.p90 was 59095.0 μs, which exceeded the expected threshold, 16666.0 μs.
  [devtools_offlinePerformanceScreen.wasm] flutter_frame.total_time.p90 was 28900.0 μs, which exceeded the expected threshold, 16666.0 μs.
```

@eyebrowsoffire any idea what would cause WASM to be significantly slower on the CI? The JS benchmarks seem to be consistent, or at least they are not exceeding the 16666 micros threshold for any of the metrics (on the CI and locally).

**Comment by yjbanov** [comment]
Does the CI use the same hardware+OS combination as the local device you use for benchmarking? A lot depends on the hardware the benchmark runs on. As for why the JS is consistent and Wasm is not, I'm not sure. Someone explained to me in the past that V8 runs in different modes for different situations. For example, when you have DevTools open, V8 switches into a mode that supports debugging, which changes the performance characteristics of the code.

**Comment by kenzieschmoll** [comment]
@yjbanov looks like switching the action to run on `macos-latest` instead of `ubuntu-latest` did the trick. Thanks!

**Pull request merged**
