### PR TITLE
Add a DEMO banner to the layout details tab

### PR DESCRIPTION
**Pull request by DaveShuckerow**
image

### CODE REVIEW

**Comment by DaveShuckerow** [comment]
> can the banner say "EXPERIMENT" instead of demo?
> We should probably also give an option to hide the banner as I wouldn't want to demo with the banner.

We're space-constrained:

image

Regardless of the text, this is only useful if we're able to turn this feature on in the release build.

**Comment by jacob314** [comment]
Looks like the word `EXPERIMENT` would barely fix.

**Comment by DaveShuckerow** [comment]
> Looks like the word `EXPERIMENT` would barely fix.

Everything except the end of the T is there.

**Comment by devoncarew** [comment]
> > Looks like the word `EXPERIMENT` would barely fix.
> 
> Everything except the end of the T is there.

Perhaps:

```
Under
Development
```

on two separate lines?

**Comment by DaveShuckerow** [comment]
> > > Looks like the word `EXPERIMENT` would barely fix.
> > 
> > 
> > Everything except the end of the T is there.
> 
> Perhaps:
> 
> ```
>    Under
> Development
> ```
> 
> on two separate lines?

The banner paint only fits one line of text.  `DEVELOPMENT` is also longer than `EXPERIMENT`.

**Comment by DaveShuckerow** [comment]
`PROTOTYPE` does fit properly.  If there's no objections, I'll merge that.

image

**Pull request merged**
