### PR TITLE
Added host argument

### PR DESCRIPTION
**Pull request by Raieen**
Hi,

This pull request adds a new command line argument, host. This allows a user to specify the host they want DevTools to run on and defaults to localhost if the host is not passed in.

Currently there is no way to change to change the host for DevTools as it defaults to localhost. Since this feature exists for Dart Observatory (i.e. --enable-vm-service=8181/0.0.0.0), it would be nice to have the same feature in DevTools.

### CODE REVIEW

**Comment by Raieen** [comment]
@googlebot I signed it!

**Comment by Raieen** [comment]
Hi, it looks like one of the tests is failing due to
```
Unable to connect to Chrome debug port: 39187
   SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 59818
```

If the test runs again and passes, is there any action on me to get this merged in?

**Comment by devoncarew** [comment]
That failure is likely unrelated to the PR. Can you update this PR with the latest from master and re-push to your branch? That will kick off the tests again (and make sure this works with the latest source from master). Thanks!

**Comment by devoncarew** [comment]
@Raieen - the CIs are green now; merging. Thanks for the contribution!

**Pull request merged**
