### PR TITLE
fix workflows/build.yaml file syntax

### PR DESCRIPTION
**Pull request by devoncarew**
- fix workflows/build.yaml file syntax
- more work towards https://github.com/flutter/devtools/issues/2454

### CODE REVIEW

**Comment by devoncarew** [comment]
🎈 it's working :)

**Comment by devoncarew** [comment]
Will need to work on getting the various bits of the matrix working now.

**Comment by devoncarew** [comment]
(TBR)

**Review by kenzieschmoll — COMMENTED** [review]
lgtm_army

**Pull request merged**
