### PR TITLE
address a few issues with dark mode and the debugger

### PR DESCRIPTION
**Pull request by devoncarew**
- address a few issues with dark mode and the debugger
- use zenburn in the editor area
- tweak debugger breakpoints, execution point visualization
- make the dark theme background color less dark
- address parts of https://github.com/flutter/devtools/issues/418

Screen Shot 2019-03-12 at 9 19 40 AM

### CODE REVIEW

**Comment by jacob314** [comment]
The new overall background color looks good. 

The zen-burn background color looks a bit lighter than the title bar of the application. I would suggest either tweaking our title bar color to match zenburn or tweaking the background for zenburn to match the title bar.

What do you think of making the callstack/breakpoint/scripts area match the zenburn background color? That could look a bit more consistent or might look odd.

**Comment by devoncarew** [comment]
> The zen-burn background color looks a bit lighter than the title bar of the application. I would suggest either tweaking our title bar color to match zenburn or tweaking the background for zenburn to match the title bar.

It likely looks lighter since the area is larger; it's the same css, but I believe that colors are perceived as lighter when in larger swatches. We could lighten or darken the title bar color for improved contrast with zenburn?

> What do you think of making the callstack/breakpoint/scripts area match the zenburn background color? That could look a bit more consistent or might look odd.

+1, I think that would look good; I'll give it a shot

**Comment by devoncarew** [comment]
Screen Shot 2019-03-12 at 9 59 06 AM

**Comment by devoncarew** [comment]
updated -

**Comment by jacob314** [comment]
LGTM!

**Pull request merged**
