### PR TITLE
Update DevTools to Material 3

### PR DESCRIPTION
**Pull request by kenzieschmoll**
Fixes https://github.com/flutter/devtools/issues/4601

There is still some polish to land as a follow up and some TODOs I will address, but this is the bulk of the migration.

RELEASE_NOTE_EXCEPTION=[release notes are modified - there is a bug in the check]

### CODE REVIEW

**Review by polina-c — APPROVED** [review]

**Comment by bkonyi** [comment]
Some places that need UI polish:

There's some places where the border outline is cut off at the corners (debugger call stack, file explorer, network requests table, logging, etc):

image

and some buttons with colored backgrounds have invisible text (connection screen, device info dialog):

image

Text is unreadable in the heap snapshot tab:

image

We need some padding between the "Clear" and "(?)" buttons under the trace instances tab:

image

The "File Explorer" button on the debugger page should be a toggle button:

image

**Comment by bkonyi** [comment]
Light theme review:

Selected text contrast is low for table rows with light theme enabled (also there's no alternating colors between rows):

image

Not sure if this is due to this migration, but the memory chart legend is clipping text:
image

Logging screen labels have poor contrast:

image

I think we should consider revisiting our color scheme for the light theme. There's very little color and the colors we do have feel rather harsh:

image

It feels like Windows high-contrast mode, which I'm not sure is the look we should go for:

image

**Comment by CoderDake** [comment]
Code looks good. I did some testing and found the following issues
- [ ] Landing page buttons aren't readable

Screenshot 2023-03-17 at 9 52 30 AM
Screenshot 2023-03-17 at 9 52 15 AM
- [ ] Cpu sample rate background is square, but button is round:
Screenshot 2023-03-17 at 9 57 52 AM
- [ ] Memory page line height seems to cut off the text
Screenshot 2023-03-17 at 9 59 42 AM
- [ ] Debugger button hover backgrounds are square
Screenshot 2023-03-17 at 10 02 08 AM
- [ ] Device info button not readable
Screenshot 2023-03-17 at 10 06 58 AM

**Comment by CoderDake** [comment]
@kenzieschmoll do you know if these material changes would fix this failure on master?
https://github.com/flutter/devtools/actions/runs/4445404285/jobs/7804598873

**Comment by CoderDake** [comment]
For now kenzie is adding a release notes exception to the description to overcome a bug in the release notes workflow.
I've filed an issue for it here.
https://github.com/flutter/devtools/issues/5439

Essentially this PR has so many files, and the workflow doesn't support pagination when fetching the list of files modified :P :D

**Comment by kenzieschmoll** [comment]
> > @kenzieschmoll do you know if these material changes would fix this failure on master? https://github.com/flutter/devtools/actions/runs/4445404285/jobs/7804598873
> 
> Those failures look unrelated. Those are for case study apps. Something probably is broken with those apps on the the latest version of the flutter candidate.

I added fixes for this to this PR. Just changed a couple min sdk constraints on the test fixture and case study apps

**Pull request merged**
