### PR TITLE
more dependency bumps

### PR DESCRIPTION
**Pull request by jonahwilliams**
Unblock latest test in flutter tools by bumping shelf_static dep, also bumps usage while its here

### CODE REVIEW

**Comment by kenzieschmoll** [comment]
the version of all the devtools packages are pegged. from the main `devtools` directory, run `./tools/update_version.sh 2.0.0+3` to update all the versions. Then be sure to add an entry to `devtools/packages/devtools/CHANGELOG.md` for 2.0.0+3

**Review by kenzieschmoll — APPROVED** [review]

**Comment by jonahwilliams** [comment]
I believe the breakage of debugLabel is being reverted in flutter, and is unrelated to this PR

**Comment by kenzieschmoll** [comment]
If the change has already been reverted, can we re-run the bots to pick up latest flutter?

**Comment by jonahwilliams** [comment]
Flutter tree is closed so we might need to wait for a bit

**Comment by jonahwilliams** [comment]
Revert is https://github.com/flutter/flutter/pull/79005

**Comment by jonahwilliams** [comment]
revert has landed

**Comment by jonahwilliams** [comment]
All tests passed, landing

**Pull request merged**
