### PR TITLE
Update row selection to resolve conflict with link color.

### PR DESCRIPTION
**Pull request by polina-c**
Fixes https://github.com/flutter/devtools/issues/5046

Screenshot 2023-01-18 at 8 08 02 AM

### CODE REVIEW

**Comment by polina-c** [comment]
@malloc-error

**Comment by kenzieschmoll** [comment]
let's make the link color white for the selected row. There is not enough contrast, as is.

**Comment by malloc-error** [comment]
I agree with Kenzie on the contrast issue. I think the most straightforward solution is as Kenzie said to make the link text white. The underline probably provides enough context that it's a link, and therefore a different category of text. 

If there's a very bright gray in the existing palette, you could try that for the link text color, to create a bit of visual distinction with the text on the left (the way the un-selected rows are with blue and black text). 

In any case, we could look into cases like this in the color audit later this quarter.

**Comment by polina-c** [comment]
Implemented in other PR: https://github.com/flutter/devtools/pull/5067

**Pull request closed without merging**
