### PR TITLE
Simplify running in VS Code

### PR DESCRIPTION
**Pull request by DanTup**
VS Code understands `pub: build_runner serve` as a task now (and has the problemMatcher internally) so we don't need quite so much junk in order to make F5 work when editing this in VS Code.

@devoncarew This shouldn't change any behaviour, and it seems to work ok in my quick testing, though I'm not actually sure if there are any significant differences between calling `webdev serve` and `pub build_runner serve` (which is what Dart Code has support for)?

### CODE REVIEW

**Comment by DanTup** [comment]
> we generally want to treat `webdev` as our entry-point for tooling

Is it stable enough that we'd be happy to ship integration with it? Currently we detect `build_runner`(?) in the pubspec to show the `build_runner` tasks, it wouldn't be difficult to also detect `webdev` and show them (presumably we'd want to hide the `build_runner` ones in that case?).

I'll land this as-is for now, but we can update it when the Dart plugin understands `webdev`.

**Comment by devoncarew** [comment]
> Is it stable enough that we'd be happy to ship integration with it?

Yes, and more work is being put into it currently.

>  it wouldn't be difficult to also detect webdev and show them (presumably we'd want to hide the build_runner ones in that case?).

This sounds reasonable; generally I think we want to either only show webdev items, or at least prefer them. My understanding is that `build_runner` is more on the level of plumbing.

**Comment by devoncarew** [comment]
I think that pub global activate will be the most common way to run it - there may not be much indication in the pubspec that its in use.

> For non-web users (Flutter, CLI) is there some equiv to webdev run the codegen/start watching?

I'm not certain here -

**Comment by DanTup** [comment]
Ok, I've opened https://github.com/Dart-Code/Dart-Code/issues/1412 about changing over - though we'll need to figure out how to identify which projects to use `webdev` for!

**Pull request merged**
