### PR TITLE
Run travis on Stable Dart channel too

### PR DESCRIPTION
**Pull request by DanTup**
I'm expecting this to fail due to #204 right now, but I'm going to look into that shortly...

### CODE REVIEW

**Comment by devoncarew** [comment]
Thinking about this, we may just need to test on one channel (dev for instance). The compiled app will include all its dependencies - app code, package code, and dart sdk code. Just testing against the version that we expect to build and distribute for is likely enough here.

**Comment by DanTup** [comment]
@devoncarew Since the above issue is fixed, this can probably be made to go green. Do you think there's any value in it, or shall we just close?

**Comment by DanTup** [comment]
(I can see a little value if we want to protect against making changes that rely on new VM service behaviour that hasn't made a stable Dart release, but I don't know how likely that is)

**Comment by devoncarew** [comment]
I think the first exceptions in #204 would still be an issue?

I don't think it's necessary to land this anymore in terms of ensuring what we're shipping is well tested, but it can't hurt. If you'd like to, feel free to land. It will help us vet out issues with various versions of the sdk, can can at least act as a forcing function to fix sdk issues.

**Comment by DanTup** [comment]
> I think the first exceptions in #204 would still be an issue?

Oh yeah, I forgot we had multiple issues. I'll rebase this on master and review the results and at least have a quick dig through them. If they can pass without much effort it makes sense to keep.

**Comment by DanTup** [comment]
02:13 +6 -1: test/integration_tests/integration_test.dart: integration debugging lists scripts [E]
  Expected: non-empty
    Actual: []

Interestingly, I saw this one on `master` earlier:

https://travis-ci.org/flutter/devtools/jobs/488555199

Not sure if the cause is the same (I wonder if there's a race or something and maybe the stable STD hits it more). I'm gonna try and get Windows sorted first (seems like a bigger benefit) but I will come back and have a look at this.

**Comment by devoncarew** [comment]
Possibly a race condition, that we almost always win on dev?

**Comment by DanTup** [comment]
That's my suspicion. I found some races on Windows so I'll see how things are when we're sorted them (see #218).

**Comment by DanTup** [comment]
I logged unhandled JS errors (#275) and tracked this down:

> getScripts: Method not found

Seems `getScripts` is not available in Dart v2.1 as it was only added late last year:

https://github.com/dart-lang/sdk/commit/7c0b22566633da8f28279d7ed7d3ece301fe545a

@devoncarew any preference on how to handle this? Should we say we require a newer Dart, or should we try to make this fail gracefully?

**Comment by DanTup** [comment]
I've opened https://github.com/flutter/devtools/issues/276 - feel free to assign a milestone depending on how important you think it is.

**Comment by devoncarew** [comment]
> I've opened #276 - feel free to assign a milestone depending on how important you think it is.

Thanks!

**Comment by DanTup** [comment]
@devoncarew This is green now - do you still think it's worth having this?

**Comment by jacob314** [comment]
Seems fine to land this.
If we ever need to only support Dev we can disable this bot.

**Pull request merged**
