### PR TITLE
 Add Call Tree to CPU profiler.

### PR DESCRIPTION
**Pull request by kenzieschmoll**
Supported features:
- Hierarchical sorting. Sort tree elements without disrupting the structure of the tree.
- Arrow key tree traversal with node expansion and collapse.
- Preserved expansion state of subtrees. When collapsing and expanding a node, the previous expansion state will be restored.
- Vertical and horizontal scrolling to support very deep (and thus wide) trees.

Screen Shot 2019-06-12 at 10 54 51 AM

TODO:
- Filtering
- Expand all / collapse all

### CODE REVIEW

**Comment by kenzieschmoll** [comment]
@DanTup  - somehow re-basing my CL made you a co-author it? Not sure how that happened...but it looks like I need your consent for this PR.

**Comment by DanTup** [comment]
I of course give my consent for you to merge my work that I didn't do 😁 however I don't know how to pass the GH checks (at least without creating a `cla: yes` label?). Possibly if you're admin you can just merge anyway (if not, I guess @jacob314 and/or @devoncarew can).

**Comment by DanTup** [comment]
You can possible fix the changeset by resetting to the previous changeset then cherry-picking this changeset (with `--no-commit`) and committing again. I don't think it'll fix the bot though, since it says this is terminal.

(not sure why it @googlebot can't support this though - if it can check the CLA for one person, surely it can check for two 🤔)

**Comment by kenzieschmoll** [comment]
Closing this PR. Took the diff and applied it to a different branch in https://github.com/flutter/devtools/pull/724. Thanks anyway, Danny.

**Pull request closed without merging**
