### PR TITLE
speed up build_runner builds

### PR DESCRIPTION
**Pull request by jakemac53**
- Use generate_for to target specific input files
- Disabling the mockito generator where it isn't used

Closes https://github.com/flutter/devtools/issues/5229

RELEASE_NOTE_EXCEPTION=Dev exp changes only

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or there is a reason for not adding tests.

### CODE REVIEW

**Comment by jakemac53** [comment]
For me this makes the devtools_app build go from a bit over a minute to <20 seconds, and takes devtools_app from >30 seconds down to under 20.

**Comment by CoderDake** [comment]
I'm excited to see how much this speeds up the Github builds 🎉

**Comment by jakemac53** [comment]
Fwiw the largest signal that you could be optimizing here is comparing the number of actions to the number of outputs, I noticed this could be optimized because I saw `[INFO] Succeeded after 1m 15s with 5 outputs (1268 actions)`, and now you get `[INFO] Succeeded after 19.1s with 5 outputs (5 actions)` (this is in devtools_app).

Some builders will have lots of optional actions so it isn't always a good signal, but for simple builds it is :)

**Review by CoderDake — APPROVED** [review]

**Comment by jakemac53** [comment]
Looks like it reduces the github action times a bit over a minute :)

**Comment by jakemac53** [comment]
@CoderDake I will let you hit the button when you are ready :)

**Comment by bkonyi** [comment]
Thanks Jake!

**Pull request merged**
